FROM almalinux:9
ADD https://raw.githubusercontent.com/vija-web/Docker/refs/heads/main/README.md /tmp

CMD ["sleep" , "3000"]

# ADD and COPY works same but the ADD will be having the extra functionality 
# i.e to download file from the internet and to untar the files