services: # here service means container
  catalogue:
    build: ./Catalogue
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  mongodb:
    build: ./Mongodb
    image: mongodb:v1
    container_name: mongodb
    volumes:   # similar to docker run -v mongodb: /data/db
      - mongodb:/data/db
  mysql:
    build: ./Mysql
    image: mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  redis:
    build: ./Redis
    image: redis:v1
    container_name: redis
    volumes:
      - redis:/data
  rabbitmq:
    build: ./Rabbitmq
    image: rabbitmq:v1
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  user:
    build: ./User
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./Cart
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  shipping:
    build: ./Shipping
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  payment:
    build: ./Payment
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user
  frontend:
    build: ./Frontend
    image: frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have alreday created the network and just want to make as default to all the containers means.
volumes:
  mongodb:  # similar to docker volume create mongodb
  mysql:
  redis:
  rabbitmq: