FROM almalinux:9
# RUN cd /tmp
WORKDIR /tmp
RUN pwd

CMD ["sleep" "5000"]

# it won't really change the /tmp directory 
# instead we should use WORKDIR
# Now it shows the /tmp path in the RUN pwd command

